name: dy-ai
on:
  schedule:
    - cron: '0 3 * * *'
jobs:
  test:
    name: dy
    runs-on: ubuntu-latest
    steps:
      - run: docker run -e DB_HOST=${{ secrets.DB_HOST }} -e DB_PORT=${{ secrets.DB_PORT }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} docker.io/gwuhaolin/dy-ai
      - name: Clear Cache
        uses: wei/curl@master
        with:
          args: http://${{ secrets.DB_HOST }}/clearCache
