name: dy
on:
  schedule:
    - cron: '0 3 * * *'
jobs:
  test:
    name: dy
    runs-on: ubuntu-latest
    steps:
      - run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ github.token }}
      - run: docker run -e DB_HOST=${{ secrets.DB_HOST }} -e DB_PORT=${{ secrets.DB_PORT }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} docker.pkg.github.com/gwuhaolin/documentary-fans/dy-server:latest
      - name: Clear Cache
        uses: wei/curl@master
        with:
          args: http://${{ secrets.DB_HOST }}/clearCache
