name: dy
on:
  schedule:
    - cron: '0 3 * * *'
jobs:
  test:
    name: dy
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker run -e DB_HOST=${{ secrets.DB_HOST }} -e DB_PORT=${{ secrets.DB_PORT }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} docker.pkg.github.com/gwuhaolin/documentary-fans/dy-fetch:latest
      - name: Clear Cache
        uses: wei/curl@master
        with:
          args: http://${{ secrets.DB_HOST }}/clearCache
