name: dy
on:
  schedule:
    - cron: '0/20 * * * *'
jobs:
  test:
    name: dy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - run: chmod +x ./dy
      - run: DB_HOST=${{ secrets.DB_HOST }} DB_PASSWORD=${{ secrets.DB_PASSWORD }} ./dy
